gen reldpri=""
replace reldpri="AmInd 		  	 " if priracgn==1	
replace reldpri="AlaskNat        " if priracgn==2	
replace reldpri="CanInd          " if priracgn==3	
replace reldpri="LatInd          " if priracgn==4	
replace reldpri="AIANAgg         " if priracgn==5	
replace reldpri="AsianInd        " if priracgn==6	
replace reldpri="Cambodian       " if priracgn==7	
replace reldpri="Chinese         " if priracgn==8	
replace reldpri="Myanmar         " if priracgn==9	
replace reldpri="Filipino        " if priracgn==10	
replace reldpri="Hmong           " if priracgn==11	
replace reldpri="Japanese        " if priracgn==12	
replace reldpri="Korean          " if priracgn==13	
replace reldpri="Laotian         " if priracgn==14	
replace reldpri="SoAsian         " if priracgn==15	
replace reldpri="Vietnamese      " if priracgn==16	
replace reldpri="AsianOth        " if priracgn==17	
replace reldpri="AsianAgg        " if priracgn==18	
replace reldpri="AfrAm           " if priracgn==19	
replace reldpri="Caribbean       " if priracgn==20	
replace reldpri="Ethiopian       " if priracgn==21	
replace reldpri="Somali          " if priracgn==22	
replace reldpri="African         " if priracgn==23	
replace reldpri="BlackOth        " if priracgn==24	
replace reldpri="BlackAgg        " if priracgn==25	
replace reldpri="HisMex          " if priracgn==26	
replace reldpri="HisCen          " if priracgn==27	
replace reldpri="HisSou          " if priracgn==28	
replace reldpri="HisOth          " if priracgn==29	
replace reldpri="HisAgg          " if priracgn==30	
replace reldpri="MidEast         " if priracgn==31	
replace reldpri="NoAfr           " if priracgn==32	
replace reldpri="MENAAgg         " if priracgn==33	
replace reldpri="Cham            " if priracgn==34	
replace reldpri="				 " if priracgn==35	
replace reldpri="                " if priracgn==36	
replace reldpri="COFA            " if priracgn==37	
replace reldpri="Marshall        " if priracgn==38	
replace reldpri="Samoan          " if priracgn==39	
replace reldpri="Tongan          " if priracgn==40	
replace reldpri="NatHaw          " if priracgn==41	
replace reldpri="NHPIoth         " if priracgn==42	
replace reldpri="NHPIAgg         " if priracgn==43	
replace reldpri="EastEur         " if priracgn==44	
replace reldpri="Slavic          " if priracgn==45	
replace reldpri="WestEur         " if priracgn==46	
replace reldpri="WhiteOth        " if priracgn==47	
replace reldpri="WhiteAgg        " if priracgn==48	
replace reldpri="                " if priracgn==50	
replace reldpri="RaceOth         " if priracgn==51	
replace reldpri="                " if priracgn==52	
replace reldpri="                " if priracgn==53	
replace reldpri="                " if priracgn==98	
replace reldpri="                " if priracgn==99	
replace reldpri="                " if priracgn==100	
replace reldpri=trim(reldpri)
assert reldpri!="" // confirm no missings
